import { readJSON, writeJSON } from '../../js/storage.js';
const EVENTS_KEY='lega.eventos';const NAV_KEY='lega.navigation.request';let state={query:'',status:'todos'};
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const dateBR=v=>{if(!v)return'—';const s=String(v).slice(0,10);const[y,m,d]=s.split('-').map(Number);return y&&m&&d?new Intl.DateTimeFormat('pt-BR').format(new Date(y,m-1,d)):'—';};
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const selectedQuote=e=>e?.orcamentos?.find(q=>q.id===e.orcamentoEscolhidoId)||e?.orcamentos?.at(-1)||null;
const rows=()=>readJSON(EVENTS_KEY,[]).flatMap(event=>(event.contratos||[]).map((contract,i)=>({event,contract,isLatest:i===(event.contratos||[]).length-1,signed:!!event.contratoAssinado,quote:contract.orcamento||selectedQuote(event)})));
export function render(){const all=rows();const filtered=all.filter(x=>{const c=x.contract.cliente||{};const q=x.quote||{};const txt=`${c.nome||''} ${c.cpf||''} ${q.nome||''} ${q.pacote||''}`.toLowerCase();const s=x.signed?'assinado':'pendente';return(!state.query||txt.includes(state.query.toLowerCase()))&&(state.status==='todos'||state.status===s);}).sort((a,b)=>String(b.contract.createdAt||'').localeCompare(String(a.contract.createdAt||'')));const signed=all.filter(x=>x.signed).length;return `<div class="page-grid contracts-module"><section class="events-header"><div><span class="eyebrow">DOCUMENTOS</span><h2>Contratos</h2><p>Consulta dos contratos gerados dentro dos eventos. Novos contratos continuam sendo criados pelo fluxo do evento.</p></div></section><section class="budget-kpis"><div class="panel"><small>Contratos gerados</small><strong>${all.length}</strong></div><div class="panel"><small>Assinados</small><strong>${signed}</strong></div><div class="panel"><small>Aguardando assinatura</small><strong>${Math.max(0,all.length-signed)}</strong></div></section><section class="panel budget-toolbar"><div class="events-search"><span>⌕</span><input id="contractSearch" value="${esc(state.query)}" placeholder="Buscar cliente, CPF, evento ou pacote"></div><select id="contractStatus"><option value="todos">Todos</option><option value="pendente" ${state.status==='pendente'?'selected':''}>Pendentes</option><option value="assinado" ${state.status==='assinado'?'selected':''}>Assinados</option></select><span class="events-count">${filtered.length} de ${all.length}</span></section>${all.length?`<section class="panel budget-list-panel"><div class="table-wrap"><table class="event-table"><thead><tr><th>Versão</th><th>Cliente / Evento</th><th>Data do evento</th><th>Valor</th><th>Situação</th><th></th></tr></thead><tbody>${filtered.map(x=>{const c=x.contract.cliente||{};const q=x.quote||{};return `<tr><td><span class="version-badge">V${x.contract.versao||1}</span></td><td><strong>${esc(c.nome||q.cliente||'')}</strong><small>${esc(q.nome||q.tipo||'')}</small></td><td>${dateBR(q.data)}</td><td>${money(q.valor)}</td><td><span class="budget-status budget-status--${x.signed?'aceito':'escolhido'}">${x.signed?'Assinado':'Aguardando assinatura'}</span></td><td><button class="btn btn-ghost" data-action="open-contract" data-event="${x.event.id}">Abrir no evento</button></td></tr>`;}).join('')}</tbody></table></div></section>`:`<section class="panel empty-state"><div class="empty-leaf"></div><h2>Nenhum contrato gerado</h2><p>Os contratos aparecerão automaticamente aqui quando forem gerados dentro dos eventos.</p></section>`}</div>`;}
export function renderContratos(){return render();}
export function mount({navigate}={}){const root=document.querySelector('#app');if(!root)return;const rerender=()=>{root.innerHTML=render();mount({navigate});};root.querySelector('#contractSearch')?.addEventListener('input',e=>{state.query=e.target.value;rerender();});root.querySelector('#contractStatus')?.addEventListener('change',e=>{state.status=e.target.value;rerender();});root.querySelectorAll('[data-action="open-contract"]').forEach(b=>b.onclick=()=>{writeJSON(NAV_KEY,{eventId:b.dataset.event,tab:'contrato'});navigate?.('eventos');});}
