import { readJSON, writeJSON } from '../../js/storage.js';
import { DEFAULT_USER } from '../../js/config.js';
import { CONFIG_PADRAO, createPriceTableForYear } from '../../core/engine/pricing.js';
const PRICE_KEY='lega.precos.vigencias';
const now=()=>new Date().toISOString();
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function baseTables(){const y=new Date().getFullYear();return[{id:`vig_${y}`,ano:y,reajuste:0,pacotes:JSON.parse(JSON.stringify(CONFIG_PADRAO.pacotes)),createdAt:now()}];}
function tables(){let t=readJSON(PRICE_KEY,null);if(!Array.isArray(t)||!t.length){t=baseTables();writeJSON(PRICE_KEY,t)}return t.sort((a,b)=>a.ano-b.ano)}
function renderPackageRows(t){return Object.entries(t.pacotes||{}).map(([nome,p])=>`<tr><td><strong>${esc(nome)}</strong></td><td><input name="convidado__${esc(nome)}" type="number" step="0.01" value="${Number(p.valorPorConvidado||0)}"></td><td><input name="hora__${esc(nome)}" type="number" step="0.01" value="${Number(p.valorHoraExtra||0)}"></td><td><input name="duracao__${esc(nome)}" type="number" step="1" min="1" value="${Number(p.duracao||0)}"></td><td>${money((p.faixas||[])[0]?.[1]||0)} a ${money((p.faixas||[]).at(-1)?.[1]||0)}</td></tr>`).join('')}
export function render(){const u=readJSON('lega.user',DEFAULT_USER);const ts=tables();const latest=ts.at(-1);return `<div class="page-grid"><section class="panel"><div class="panel-header"><div><h2>Configuração comercial</h2><p>Crie tabelas por ano usando a anterior como base. O reajuste padrão é 10%, mas pode ser editado.</p></div><span class="badge green">${ts.length} vigência(s)</span></div><form id="newSeasonForm" class="form-grid"><div class="field"><label>Ano da nova tabela</label><input name="ano" type="number" value="${Number(latest.ano)+1}" required></div><div class="field"><label>Reajuste sobre ${latest.ano}</label><input name="reajuste" type="number" value="10" step="0.01" min="0" required></div><div class="field"><label>Arredondamento</label><select name="arredondamento"><option value="10">Para R$ 10</option><option value="50">Para R$ 50</option><option value="0">Não arredondar</option></select></div><div><button class="btn btn-primary" type="submit">Gerar nova tabela</button></div></form><p style="margin-top:8px;color:var(--muted,#666);font-size:13px">Se pular anos (ex.: só existe ${latest.ano} e você criar ${Number(latest.ano)+3}), o reajuste é composto ano a ano, não aplicado de uma vez só.</p></section><section class="panel"><div class="panel-header"><div><h2>Tabelas de preços</h2><p>Edite a tabela selecionada. Orçamentos já emitidos preservam os valores usados.</p></div><select id="tableSelect">${ts.map(t=>`<option value="${t.ano}" ${t.ano===latest.ano?'selected':''}>${t.ano}</option>`).join('')}</select></div><form id="priceTableForm"><input type="hidden" name="ano" value="${latest.ano}"><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:left;padding:10px">Pacote</th><th style="text-align:left;padding:10px">Por convidado</th><th style="text-align:left;padding:10px">Hora extra</th><th style="text-align:left;padding:10px">Duração (horas)</th><th style="text-align:left;padding:10px">Faixas atuais</th></tr></thead><tbody id="priceRows">${renderPackageRows(latest)}</tbody></table></div><div class="form-actions"><button class="btn btn-primary">Salvar valores de ${latest.ano}</button></div></form></section><section class="panel"><div class="panel-header"><div><h2>Usuário conectado</h2><p>O perfil é reconhecido pelo login cadastrado no Supabase.</p></div><span class="badge green">Online</span></div><div class="form-grid"><div class="field"><label>Nome</label><input value="${esc(u.name)}" disabled></div><div class="field"><label>Função</label><input value="${esc(u.role||'Administrador')}" disabled></div><div class="field"><label>E-mail</label><input value="${esc(u.email||'')}" disabled></div><div><button class="btn btn-ghost" type="button" data-action="logout">Sair da Plataforma</button></div></div></section></div>`}
export function mount({renderUser,navigate}){const root=document.querySelector('#app');const select=root.querySelector('#tableSelect');select?.addEventListener('change',()=>{const t=tables().find(x=>String(x.ano)===select.value);root.querySelector('#priceRows').innerHTML=renderPackageRows(t);root.querySelector('#priceTableForm [name="ano"]').value=t.ano;root.querySelector('#priceTableForm .btn').textContent=`Salvar valores de ${t.ano}`});root.querySelector('#newSeasonForm')?.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());let ts=tables();const ano=Number(d.ano);if(ts.some(t=>t.ano===ano)){alert('Já existe uma tabela para esse ano.');return}const resultado=createPriceTableForYear(ts,ano,Number(d.reajuste),Number(d.arredondamento||0));if(!resultado){alert('Não foi possível criar a tabela: não há uma tabela anterior para usar como base.');return}ts=[...ts,...resultado.todasNovas].sort((a,b)=>a.ano-b.ano);writeJSON(PRICE_KEY,ts);navigate('configuracoes')});root.querySelector('#priceTableForm')?.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());let ts=tables();const t=ts.find(x=>x.ano===Number(d.ano));Object.keys(t.pacotes).forEach(nome=>{t.pacotes[nome].valorPorConvidado=Number(d[`convidado__${nome}`]||0);t.pacotes[nome].valorHoraExtra=Number(d[`hora__${nome}`]||0);t.pacotes[nome].duracao=Number(d[`duracao__${nome}`]||t.pacotes[nome].duracao||0)});t.updatedAt=now();writeJSON(PRICE_KEY,ts);alert(`Tabela de ${t.ano} salva.`)})}
