import { readJSON, writeJSON } from '../../js/storage.js';
import { DEFAULT_USER } from '../../js/config.js';
const PRICE_KEY='lega.precos.vigencias';
const CONFIG_KEY='lega.orcamentos.config';
const now=()=>new Date().toISOString();
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function baseTables(){const cfg=readJSON(CONFIG_KEY,{pacotes:{}});const y=new Date().getFullYear();return[{id:`vig_${y}`,ano:y,reajuste:0,pacotes:JSON.parse(JSON.stringify(cfg.pacotes||{})),createdAt:now()}];}
function tables(){let t=readJSON(PRICE_KEY,null);if(!Array.isArray(t)||!t.length){t=baseTables();writeJSON(PRICE_KEY,t)}return t.sort((a,b)=>a.ano-b.ano)}
function renderPackageRows(t){return Object.entries(t.pacotes||{}).map(([nome,p])=>`<tr><td><strong>${esc(nome)}</strong></td><td><input name="convidado__${esc(nome)}" type="number" step="0.01" value="${Number(p.valorPorConvidado||0)}"></td><td><input name="hora__${esc(nome)}" type="number" step="0.01" value="${Number(p.valorHoraExtra||0)}"></td><td>${money((p.faixas||[])[0]?.[1]||0)} a ${money((p.faixas||[]).at(-1)?.[1]||0)}</td></tr>`).join('')}
export function render(){const u=readJSON('lega.user',DEFAULT_USER);const ts=tables();const latest=ts.at(-1);return `<div class="page-grid"><section class="panel"><div class="panel-header"><div><h2>Configuração comercial</h2><p>Crie tabelas por ano usando a anterior como base. O reajuste padrão é 10%, mas pode ser editado.</p></div><span class="badge green">${ts.length} vigência(s)</span></div><form id="newSeasonForm" class="form-grid"><div class="field"><label>Ano da nova tabela</label><input name="ano" type="number" value="${Number(latest.ano)+1}" required></div><div class="field"><label>Reajuste sobre ${latest.ano}</label><input name="reajuste" type="number" value="10" step="0.01" min="0" required></div><div class="field"><label>Arredondamento</label><select name="arredondamento"><option value="10">Para R$ 10</option><option value="50">Para R$ 50</option><option value="0">Não arredondar</option></select></div><div><button class="btn btn-primary" type="submit">Gerar nova tabela</button></div></form></section><section class="panel"><div class="panel-header"><div><h2>Tabelas de preços</h2><p>Edite a tabela selecionada. Orçamentos já emitidos preservam os valores usados.</p></div><select id="tableSelect">${ts.map(t=>`<option value="${t.ano}" ${t.ano===latest.ano?'selected':''}>${t.ano}</option>`).join('')}</select></div><form id="priceTableForm"><input type="hidden" name="ano" value="${latest.ano}"><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:left;padding:10px">Pacote</th><th style="text-align:left;padding:10px">Por convidado</th><th style="text-align:left;padding:10px">Hora extra</th><th style="text-align:left;padding:10px">Faixas atuais</th></tr></thead><tbody id="priceRows">${renderPackageRows(latest)}</tbody></table></div><div class="form-actions"><button class="btn btn-primary">Salvar valores de ${latest.ano}</button></div></form></section><section class="panel"><div class="panel-header"><div><h2>Perfil do usuário</h2><p>O nome configurado aparece na saudação e no cabeçalho.</p></div><span class="badge green">Configuração local</span></div><form id="userForm" class="form-grid"><div class="field"><label for="userName">Nome de exibição</label><input id="userName" value="${esc(u.name)}" required></div><div class="field"><label for="userRole">Função</label><select id="userRole"><option ${u.role==='Administrador'?'selected':''}>Administrador</option><option ${u.role==='Financeiro'?'selected':''}>Financeiro</option><option ${u.role==='Recepção'?'selected':''}>Recepção</option><option ${u.role==='Estoque'?'selected':''}>Estoque</option></select></div><div><button class="btn btn-primary" type="submit">Salvar perfil</button></div></form></section></div>`}
export function mount({renderUser,navigate}){const root=document.querySelector('#app');const select=root.querySelector('#tableSelect');select?.addEventListener('change',()=>{const t=tables().find(x=>String(x.ano)===select.value);root.querySelector('#priceRows').innerHTML=renderPackageRows(t);root.querySelector('#priceTableForm [name="ano"]').value=t.ano;root.querySelector('#priceTableForm .btn').textContent=`Salvar valores de ${t.ano}`});root.querySelector('#newSeasonForm')?.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());let ts=tables();const ano=Number(d.ano);if(ts.some(t=>t.ano===ano)){alert('Já existe uma tabela para esse ano.');return}const source=[...ts].sort((a,b)=>a.ano-b.ano).filter(t=>t.ano<ano).at(-1)||ts.at(-1);const rate=1+Number(d.reajuste||0)/100;const round=Number(d.arredondamento||0);const cp=JSON.parse(JSON.stringify(source.pacotes));Object.values(cp).forEach(p=>{const adj=v=>{const n=Number(v||0)*rate;return round?Math.round(n/round)*round:Number(n.toFixed(2))};p.valorPorConvidado=adj(p.valorPorConvidado);p.valorHoraExtra=adj(p.valorHoraExtra);p.faixas=(p.faixas||[]).map(([lim,val])=>[lim,adj(val)])});ts.push({id:`vig_${ano}`,ano,reajuste:Number(d.reajuste),origemAno:source.ano,pacotes:cp,createdAt:now()});writeJSON(PRICE_KEY,ts);navigate('configuracoes')});root.querySelector('#priceTableForm')?.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());let ts=tables();const t=ts.find(x=>x.ano===Number(d.ano));Object.keys(t.pacotes).forEach(nome=>{t.pacotes[nome].valorPorConvidado=Number(d[`convidado__${nome}`]||0);t.pacotes[nome].valorHoraExtra=Number(d[`hora__${nome}`]||0)});t.updatedAt=now();writeJSON(PRICE_KEY,ts);alert(`Tabela de ${t.ano} salva.`)});root.querySelector('#userForm')?.addEventListener('submit',e=>{e.preventDefault();writeJSON('lega.user',{name:root.querySelector('#userName').value.trim()||'Usuário',role:root.querySelector('#userRole').value});renderUser();navigate('dashboard')})}
